export const CREATE_SELLER_SUCCSESS = 'CREATE_SELLER';
export const LOAD_SELLERS_SUCCESS = 'LOAD_SELLERS_SUCCESS';
export const GET_SELLER_BY_ID_SUCCESS = 'GET_SELLER_BY_ID_SUCCESS';
export const GET_SELLER_BY_ID_FAILURE = 'GET_SELLER_BY_ID_FAILURE';
